language: python
python:
  - "3.6"

branches:
  except:
  - /^pr_.+$/

install:
  - pip install kodi-addon-checker

before_script:
  - cd $HOME

script:
  - kodi-addon-checker $TRAVIS_BUILD_DIR --branch=jarvis
