name: Add-on Validations

on:
  push:
    branches: [ master, main ]

  pull_request:
    branches: [ master, main ]

jobs:

  addon-validations:
    if: github.repository == 'anxdpanic/script.common.plugin.cache'

    name: Add-on Validations
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python v3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Checkout Add-on
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install git+https://github.com/xbmc/addon-check.git

      - name: Kodi Add-on Checker (Nexus)
        id: kodi-addon-checker-nexus
        run: |
          kodi-addon-checker ${{ github.event.repository.name }} --branch=nexus
