name: Sync addon metadata translations

on:
  push:
    branches: [ master, main ]
    paths:
      - '**addon.xml'
      - '**resource.language.**strings.po'

jobs:
  default:
    if: github.repository == 'anxdpanic/script.common.plugin.cache'

    runs-on: ubuntu-latest

    steps:

      # Checkout the current repository into the 'project' directory
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: project

      # Setup python version 3.9
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install all dependencies required by the following steps
      # - git+https://github.com/xbmc/sync_addon_metadata_translations.git: main script for this action
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install git+https://github.com/xbmc/sync_addon_metadata_translations.git

      # Run the sync-addon-metadata-translations against the 'project' directory
      # Ran when the repository is not 'xbmc/xbmc' or 'kodi-game/controller-topology-project'
      - name: Run sync-addon-metadata-translations (Default)
        if: github.repository != 'xbmc/xbmc' && github.repository != 'kodi-game/controller-topology-project'
        run: |
          sync-addon-metadata-translations
        working-directory: ./project

      # Run the sync-addon-metadata-translations against add-ons provided with Kodi
      # Ran when the repository is 'xbmc/xbmc'
      - name: Run sync-addon-metadata-translations (xbmc/xbmc)
        if: github.repository == 'xbmc/xbmc'
        run: |
          sync-addon-metadata-translations --path ./skin.estuary/
          sync-addon-metadata-translations --path ./skin.estouchy/
          sync-addon-metadata-translations --path ./audioencoder.kodi.builtin.aac/
          sync-addon-metadata-translations --path ./audioencoder.kodi.builtin.wma/
          sync-addon-metadata-translations --path ./screensaver.xbmc.builtin.dim/
        working-directory: ./project/addons

      # Run the sync-addon-metadata-translations against all add-ons in the repo
      # Ran when the repository is 'kodi-game/controller-topology-project'
      - name: Run sync-addon-metadata-translations (kodi-game/controller-topology-project)
        if: github.repository == 'kodi-game/controller-topology-project'
        run: |
          sync-addon-metadata-translations --multiple-addons
        working-directory: ./project/addons

      # Create a PR with any changes made by the sync-addon-metadata-translations script
      # - title/commit message: Sync of addon metadata translations
      # - body: Sync of addon metadata translations triggered by {github.sha}
      - name: Create PR for sync-addon-metadata-translations changes
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          commit-message: Sync of addon metadata translations
          title: Sync of addon metadata translations
          body: Sync of addon metadata translations triggered by ${{ github.sha }}
          branch: amt-sync
          delete-branch: true
          path: ./project
